name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false


      - uses: actions/setup-node@v2
        with:
            node-version: '16.x'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dist/*"
          target: "~/tripnote"
          strip_components: 1
          rm: true
